/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class king_bird_ndkjnidemo_JNIUtils */

#ifndef _Included_king_bird_ndkjnidemo_JNIUtils
#define _Included_king_bird_ndkjnidemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     king_bird_ndkjnidemo_JNIUtils
 * Method:    printStringByJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_king_bird_ndkjnidemo_JNIUtils_printStringByJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
